In [1]:
import numpy as np

In [25]:
b = np.ones((2,1))
a = np.zeros((2,1))
print(a.shape)
c = np.concatenate((a, b))
print(c.shape[0])
print(c)
d = np.copy(c)
d[2][0] = 3
print(c)
print(d)
l = [1,2,3]
e = np.asarray(l).reshape(len(l), -1)
print(e)

f = np.array(e, dtype=np.float32)
print("F:", f)


inpu = f
inputs = inpu
inputs = np.concatenate((inputs, inpu))
print(inputs)

(2, 1)
4
[[0.]
 [0.]
 [1.]
 [1.]]
[[0.]
 [0.]
 [1.]
 [1.]]
[[0.]
 [0.]
 [3.]
 [1.]]
[[1]
 [2]
 [3]]
F: [[1.]
 [2.]
 [3.]]
[[1.]
 [2.]
 [3.]
 [1.]
 [2.]
 [3.]]


In [40]:
a = np.asarray([1,2,3]).reshape(3,1).reshape(-1)
b = np.asarray([1,0,2])
print(a.shape[0])
c = a * b
print(c)
d = np.zeros(5)
print(d.shape)
d[1] = 3
print(d)
print(2 in d)
print(np.sum(c))

3
[1 0 6]
(5,)
[0. 3. 0. 0. 0.]
False
7
